syntax on
set nu ai ci si nobk et ar ru nocp sm
set bs=2 ts=4 sw=4 sts=4
set cb=unnamed
set cino=g0j1J1
set bg=dark
set mouse=a
colorscheme torte
command PS vsp %:r.in|w|sp %:r.out|w|vert res 30|norm <C-w>w<C-w>w
command RIO wall|!g++ -O2 -std=c++14 -Wall -lm %:r.cpp -o %:r && ./%:r < %:r.in > %:r.out
command RI  wall|!g++ -O2 -std=c++14 -Wall -lm %:r.cpp -o %:r && ./%:r < %:r.in
command R   wall|!g++ -O2 -std=c++14 -Wall -lm %:r.cpp -o %:r && ./%:r
